Analytical APDFT in KSDFT: N2 -> CO

In [1]:
from pyscf import gto,scf
import pyscf
import numpy as np

pyscf.__version__

'2.2.1'

In [2]:
from aqa.AP_class import APDFT_perturbator as AP

In [3]:
mol_NN=gto.M(atom= "N 0 0 0; N 0 0 2.1",unit="Bohr",basis="def2-TZVP")
mf_nn=scf.RKS(mol_NN)
mf_nn.xc = 'pbe0'
# mf_nn.xc = 'lda,vwn'
# mf_nn.conv_tol = 1e-12
# mf_nn.grids.level = 3
e = mf_nn.scf(dm0=mf_nn.init_guess_by_1e())
print(mf_nn.e_tot)
print(mf_nn.energy_nuc())
mf_nn.nuc_grad_method().kernel()
ap_nn=AP(mf_nn,sites=[0,1])
print(mf_nn.mol.atom_coords())

converged SCF energy = -109.444982309111
-109.44498230911076
23.333333333333332
--------------- RKS gradients ---------------
         x                y                z
0 N    -0.0000000000     0.0000000000    -0.0623740387
1 N     0.0000000000    -0.0000000000     0.0623740387
----------------------------------------------
[[0.  0.  0. ]
 [0.  0.  2.1]]


Calculate $\partial E/\partial Z_i$, hessian $\partial^2E/\partial Z_i\partial Z_j$ and cubic derivatives $\partial^3E/\partial Z_i\partial Z_j\partial Z_k$

In [4]:
print(ap_nn.build_elec_gradient())
print(ap_nn.build_elec_hessian())
print(ap_nn.build_cubic())

[-21.63766852 -21.63766852]
[[-3.22401997e+00 -2.94149267e-03]
 [-2.94149267e-03 -3.22401997e+00]]
[[[-0.17449351  0.10654678]
  [ 0.10654678  0.10654678]]

 [[ 0.10654678  0.10654678]
  [ 0.10654678 -0.17449351]]]


CO

In [5]:
print(ap_nn.elec_APDFT0(np.asarray([-1,1])))
print(ap_nn.elec_APDFT1(np.asarray([-1,1])))
print(ap_nn.elec_APDFT2(np.asarray([-1,1])))
print(ap_nn.elec_APDFT3(np.asarray([-1,1])))

-132.77831564244408
-132.77831564198607
-135.9993941212982
-135.99939412130507


OC

In [6]:
print(ap_nn.elec_APDFT0(np.asarray([1,-1])))
print(ap_nn.elec_APDFT1(np.asarray([1,-1])))
print(ap_nn.elec_APDFT2(np.asarray([1,-1])))
print(ap_nn.elec_APDFT3(np.asarray([1,-1])))

-132.77831564244408
-132.7783156429021
-135.99939412221423
-135.99939412220735


In [7]:
mol_CO=gto.M(atom= "C 0 0 0; O 0 0 2.1",unit="Bohr",basis="def2-TZVP")
mf_co=scf.RKS(mol_CO)
mf_co.xc = 'pbe0'
e = mf_co.scf(dm0=mf_co.init_guess_by_1e())
print(mf_co.e_tot - mf_co.energy_nuc())

converged SCF energy = -113.230628155977
-136.08777101312012
